fi.dwo.cdn: http://test-dwo-nl.s3.amazonaws.com
fi.dwo.documentbase: https://test.dwo.nl/dwo/
fi.dwo.boot: ${fi.dwo.cdn}/bundles/toolloader.jar
fi.dwo.target: numworx-toolloader
fi.dwo.bootloader: nl.numworx.toolloader
